#!/usr/bin/env python3
#solution for https://www.acmicpc.net/problem/6603

from sys import stdin 

def subsets(so_far, remain):
    if len(so_far) ==6 : # select 6 integers 
        print(so_far) 
    subsets([remain[0]],remain[1:])
    subsets(so_far,remain[1:]) 

if __name__ == '__main__' : 
    for line in stdin: 
        arr = [int(i) for i in line.split() ]
        k = arr[0]
        subset = arr[1:] 
        subsets([],subset) 
        print() 
